const modalTypes = {
  BUCKET_LIST_SELECT_CATEGORY: 'Categories',
  BUCKET_LIST_TARGET_DATE: 'Target Date',
  BUCKET_LIST_WEBSITE: 'Website',
  BUCKET_LIST_BUDGET: 'Budget',
  BUCKET_LIST_THINGS_TO_DO: 'Things to do',
  PROFILE_GENDER: 'Gender',
  PENDING_BUCKET_LIST_ITEM: 'PENDING_BUCKET_LIST_ITEM',
  ACHIEVED_BUCKET_LIST_ITEM: 'PENDING_BUCKET_LIST_ITEM',
  DELETE_JOURNAL: 'DELETE_JOURNAL',
  DELETE_BUCKET_LIST: 'DELETE_BUCKET_LIST',
};

export default modalTypes;
